name: Node.js Code Check
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Button für manuelles Auslösen der Pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Quellcode auschecken
      uses: actions/checkout@v4
    - name: Node.js einrichten
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Alle JavaScript-Dateien mit >node --check< prüfen
      run: |
        while IFS= read -r file
        do
          node --check "$file"
        done < <(find . -name "*.js")
